# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menulist',
            name='excludes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menulist',
            name='order_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menulist',
            name='order_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='menulist',
            name='order_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='menulist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
