# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0005_auto_20200117_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='order_name',
            field=models.CharField(blank=True, choices=[('chicken Double Sasuage', 'Chicken Double Sausage'), ('Chiken Single Sausage', 'Chicken Single Sausage'), ('Chicken Plain', 'Chicken Plain'), ('Beef Double Sausage', 'Beef Double Sauage'), ('Beef Single Sausuage', 'Beef Single Sauage'), ('Beef Plain', 'Beef Plain'), ('Double Hotodog', 'Double Hotdog')], max_length=25, null=True),
        ),
    ]
