# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0007_auto_20200117_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='order_upload',
            field=models.ImageField(blank=True, null=True, upload_to='Order_Pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='spot_logo'),
        ),
    ]
