# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-20 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0009_auto_20200120_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='order_upload',
            field=models.ImageField(default='mypics.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='mypics.jpg', upload_to=''),
        ),
    ]
