# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-20 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0010_auto_20200120_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='order_upload',
            field=models.ImageField(default='mypics.jpg', upload_to='Order_pics'),
        ),
    ]
